Updated relayers to accept prize pool as a parameter
GenerationSoftware/pt-v5-draw-auction pull request #48
Opened 2024-02-14 20:19 UTC by asselstine

The Prize Pool no longer has an owner, so in order to deploy we need to remove the prize pool from the constructor of the relayers.

2024-02-15 21:48 UTC, trmid requested changes

2024-02-15 21:48 UTC, trmid commented on src/RngRelayAuction.sol
>      requireAuctionOpen(_sequenceId, _rngCompletedAt)
This will only work for the first prize pool that it relays to since the `sequenceId` will be updated on the first successful call, causing all subsequent prize pool relays to fail. Someone can exploit this by spinning up a dummy prize pool and front run the relay to grief the auction.

2024-02-15 21:48 UTC, trmid commented on src/RngRelayAuction.sol
>      requireAuctionOpen(_sequenceId, _rngCompletedAt)
If the relay accepts any prize pool, then all state variables must be mapped to that prize pool. (auction results and last sequence ID)

2024-02-15 21:48 UTC, trmid commented on src/RngRelayAuction.sol
> +  event RngSequenceCompleted(uint32 indexed sequenceId, PrizePool indexed prizePool, uint32 indexed drawId);
Missing natspec param for `prizePool`

2024-02-15 21:53 UTC, trmid requested changes

2024-02-15 21:53 UTC, trmid commented on src/RngAuctionRelayerRemoteOwnerArbitrum.sol
> +    PrizePool remotePrizePool,
missing natspec param

2024-02-15 21:53 UTC, trmid commented on src/RngAuctionRelayerRemoteOwnerArbitrum.sol
> +    PrizePool _remotePrizePool,
missing natspec param

2024-02-15 21:53 UTC, trmid commented on src/RngAuctionRelayerRemoteOwnerOptimism.sol
> +    PrizePool remotePrizePool,
missing natspec param

2024-02-15 21:53 UTC, trmid commented on src/RngAuctionRelayerRemoteOwnerOptimism.sol
> +    PrizePool _remotePrizePool,
missing natspec param

2024-02-15 21:53 UTC, trmid commented on src/RngRelayAuction.sol
> +    PrizePool _prizePool,
missing natspec param

2024-02-15 21:53 UTC, trmid commented on src/RngRelayAuction.sol
> +    PrizePool _prizePool,
missing natspec param

2024-02-15 21:53 UTC, trmid commented on src/abstract/RngAuctionRelayer.sol
> +  function _encodeCalldata(PrizePool _prizePool, address _rewardRecipient) internal returns (bytes memory) {
missing natspec param

2024-02-15 21:53 UTC, trmid commented on src/interfaces/IRngAuctionRelayListener.sol
> +    PrizePool prizePool,
missing natspec param

2024-02-15 23:46 UTC, asselstine commented on src/RngRelayAuction.sol
>      requireAuctionOpen(_sequenceId, _rngCompletedAt)
Good call!  I moved the last AuctionResult into a mapping for each Prize Pool so that they can't interfere with eachother.

I realized that the last sequence id didn't have a clear purpose; so I removed it entirely

2024-02-16 14:54 UTC, trmid requested changes
Removing the sequence logic seems risky unless we commit to removing all bridging implementations. Quoted from my reply:

> The `sequenceId` protects against bridging edge cases where the rng data is bridged on sequence `n`, but there could be some delays or downtimes that cause the relay to be executed on the L2 in sequence `n+1`. The rngCompletedAt doesn't necessarily protect against this since the RNG could have delays of it's own, causing the completion to occur late in the sequence, meaning that the auction duration extends into the next sequence. This edge case is a problem because it means that the RNG for draw `n+1` is publicly known *before* the draw closes, meaning that TWAB can be manipulated to the advantage of some winners until it closes.
> 
> If we commit to no longer bridging RNG data, the sequence logic can be completely removed, but unless we remove the bridging contracts from this repo, I'd suggest that we keep it.

Also, this may be for a separate ticket, but I'm noticing that our bridging contracts use contract types for addresses that exist on the L2. For example, the `remotePrizePool` is only a `PrizePool` type on the L2 and it is not callable as such on the L1. I think it makes more sense to leave these as `address` types on L1 since the interface is not actually accessible. The same goes for `RemoteOwner`.

2024-02-16 14:54 UTC, trmid commented on src/RngRelayAuction.sol
> +    // console2.log("elapsed", elapsed);
remove comments

2024-02-16 14:54 UTC, trmid commented on src/RngRelayAuction.sol
> +    // console2.log("_computeElapsed block.timestamp", block.timestamp);
remove comments

2024-02-16 14:54 UTC, trmid commented on src/RngRelayAuction.sol
> +      emit AuctionRewardAllocated(_sequenceId, auctionResults[i].recipient, i, _reward);
Just realized that the prize pool should also be emitted in this event now.

2024-02-16 14:54 UTC, trmid commented on src/RngRelayAuction.sol
>      requireAuctionOpen(_sequenceId, _rngCompletedAt)
The `sequenceId` protects against bridging edge cases where the rng data is bridged on sequence `n`, but there could be some delays or downtimes that cause the relay to be executed on the L2 in sequence `n+1`. The rngCompletedAt doesn't necessarily protect against this since the RNG could have delays of it's own, causing the completion to occur late in the sequence, meaning that the auction duration extends into the next sequence. This edge case is a problem because it means that the RNG for draw `n+1` is publicly known *before* the draw closes, meaning that TWAB can be manipulated to the advantage of some winners until it closes.

If we commit to no longer bridging RNG data, the sequence logic can be completely removed, but unless we remove the bridging contracts from this repo, I'd suggest that we keep it.

2024-02-16 17:32 UTC, asselstine commented on src/RngRelayAuction.sol
>      requireAuctionOpen(_sequenceId, _rngCompletedAt)
Ahhh yes, good point.  If the RNG was very delayed, then it could be used for two draws.

2024-02-16 19:41 UTC, closed without merging